name: 'Deploy Azure AD B2C TrustFramework KeySet secret'
description:
  'A GitHub Action for deploying TrustFramework KeySet secrets using the
  Microsoft Graph'
author: 'Fares Manadi'

branding:
  icon: 'lock'
  color: 'blue'

inputs:
  name:
    description: 'The TrustFramework KeySet container name'
    required: false
  options:
    description: 'The TrustFramework KeySet container options'
    type: choice
    options:
      - generate
      - manual
      - upload
  policy_keys:
    description: 'The TrustFramework KeySet secret value'
  key_use:
    description:
      'The TrustFramework KeySet container usage: "Signature" or "Encryption"'
    type: choice
    options:
      - signature
      - encryption
  activation_date:
    description: 'The TrustFramework KeySet secret value'
  expiration_date:
    description: 'The TrustFramework KeySet secret value'
  key_type:
    description: 'The TrustFramework KeySet container type'
    type: choice
    options:
      - OCT
      - RSA
  secret:
    description: 'The TrustFramework KeySet secret value'
    required: false
  file_path:
    description: 'The TrustFramework KeySet secret value'
    required: false
  certificate_kind:
    description: 'Type of the uploaded certificate'
    required: false
    type: choice
    options:
      - X509
      - PKCS12
  password:
    description: 'The TrustFramework KeySet secret value'
    required: false
  tenant_id:
    description:
      'The full Azure AD B2C tenant name (e.g.: mytenant.onmicrosoft.com) or
      GUID'
    required: true
  client_id:
    description:
      'The Client ID for a service principal which will be used to authenticate
      to the Microsoft Graph'
    required: true
  client_secret:
    description:
      'The Client Secret for a service principal which will be used to
      authenticate to the Microsoft Graph'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
